apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: image-acquirer
  name: image-acquirer
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi